### ISSUE TITLE
Could not execute discoverReaders because the SDK is busy with another command: discoverReaders.

### ISSUE THREAD

**Issue by katharinepadilha** [stripe/stripe-terminal-react-native#349]
**Describe the bug**
I can't fetch readers after an unsuccessful search

**To Reproduce**

1. Run `discoverReaders` without any reader available
2. It won't return any reader, try again, and an error will prompt  -> `[Stripe terminal]: didFinishDiscoveringReaders {"error": {"code": "Busy", "message": "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders."}}`
4. Try to cancel the discovery with`cancelDiscovering` -> `{"error": {"code": "CancelFailedAlreadyCompleted", "message": "discoverReaders could not be canceled because the command has already been canceled or has completed."}}`
5. Can't leave this situation until close the app and reopen

**Expected behavior**
I believe we should be able to cancel and retry as many times we need to find a reader

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS: 15.5

**Comment by jdivock-stripe** [comment]
Hey @katharinepadilha thanks for the report, let me see if I can repro on my end.

**Comment by c-fitzmaurice** [comment]
I had this same error and have noticed two things:

1. This occurs if you don't use `await cancelDiscovering();`
2. If React Native reloads during discovery you can't cancel without quitting and rebooting the app.

**Comment by arekkubaczkowski** [comment]
@katharinepadilha @c-fitzmaurice 
thanks for the detailed report. I am going to prevent the SDK to call `discoverReaders` twice in a row since that introduced a bug by losing previous reference. It means that you will be still able to call `cancelDiscovering` method even if you called `discoverReaders` twice before. However, we recommend to prevent user to do it also on the implementation side as there is no reason to allow for calling `discoverReaders` when the previous call is not canceled or completed yet.

Regarding the second point, I will try to investigate it deeper but it could be a little tricky to support react native reloads as we lose an access to all of the references on native side.
Ideally if SDK would break the connection on reload and allow to the new one but this would require native SDK's (ios, android) to expose some method for the hard reset of the SDK.

cc @jdivock-stripe

**Comment by c-fitzmaurice** [comment]
Thank you @jdivock-stripe

**Comment by katharinepadilha** [comment]
Thank you @jdivock-stripe
