### ISSUE TITLE
Production has different functionality compared to simulated

### ISSUE THREAD

**Issue by oliviupis** [stripe/stripe-terminal-react-native#396]
**Describe the bug**
While working with simulated I could choose to update manually my reader and did everything according to that particular use case. When testing it on production it looks like updating is mandatory and everything I developed seems deprecated. Another issue is that on low battery if update is needed after connection immediately throws "ReaderSoftwareUpdateFailedBatteryLow" and disconnects reader and the same error I get even when reader is charging

**To Reproduce**
 On "Describe the bug" is obvious what you need to test.

**Expected behavior**
If battery is low for an update, throw a warning or even an error but do not disconnect reader

- Device: iPad Pro 2021 M1
- OS: 15.7
- Version: ^0.0.1-beta.8

**Comment by bric-stripe** [comment]
> When testing it on production it looks like updating is mandatory and everything I developed seems deprecated

This code will likely still be used. Most, but not all, updates will start as optional for 2 weeks prior to becoming required. Once the updates `requiredAt` date is passed, the update will be installed during the next connect as you're seeing.

> If battery is low for an update, throw a warning or even an error but do not disconnect reader

That's the behavior you should see if the update is announced as an optional update and your application installs it with `installAvailableUpdate`. If the reader has a low battery when `installAvailableUpdate` is used it should not disconnect the reader when the update errors.

But because the update was required to be installed prior to the reader being usable the connect call will fail for required updates.

**Comment by oliviupis** [comment]
Looking forward to see what ideas you'll have for this cases :) Somehow make it obvious in order to can display a message in this cases.

Also updating while charging, from a small percentage of battery, please somehow fix that problem :)

Thanks
