### ISSUE TITLE
[Android] Could not invoke StripeTerminalReactNative.initialize null 

### ISSUE THREAD

**Issue by mytabworks** [stripe/stripe-terminal-react-native#414]
Could not invoke StripeTerminalReactNative.initialize null 
you must request location permissions before initializing the Terminal

Also there is no exact configuration for android set up in [react native terminal docs.](https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=react-native).. because when I click the Android Tab, it is redirecting me to the stripe-terminal-android config setup which doesn't make sense to me... 

Environment
Android
@stripe/stripe-terminal-react-native@0.0.1-beta.11
react-native@0.68.5

**Comment by mytabworks** [comment]
It is now working on Emulator by adding this "requestNeededAndroidPermissions"

however when installing the app by APK and opening it. it still is crashing!!

my sentry catch the error:
<img width="872" alt="Screen Shot 2022-11-09 at 9 07 18 PM" src="https://user-images.githubusercontent.com/28913097/200838477-807462c7-b842-4c62-8cec-8a49caa816d2.png">

**Comment by nazli-stripe** [comment]
hey @mytabworks can you resubmit this following the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Stripe Terminal React Native SDK version**

- (e.g., `^0.0.1-beta.11`)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by rv-stripe** [comment]
This error is received when location services are disabled on a device level. This must be fixed on a device level by going to Settings > Location on the device and enabling Location in addition to granting the application the location permissions.

**Comment by mytabworks** [comment]
@rv-stripe Thank you for your reply, the thing is the location services is already enabled and I also grant the Application the location permissions, any thought? btw. I am using Redmi Note 9 Pro
