### ISSUE TITLE
Cannot communicate with reader if switching from ethernet to wifi

### ISSUE THREAD

**Issue by melarts** [stripe/stripe-terminal-react-native#418]
**Describe the bug**

Cannot communicate with reader if switching from ethernet to WiFi.

**To Reproduce**
1. Start a discovery while the reader is connected via ethernet (but also trough wifi). Then the IP linked to the reader is the ethernet IP. 
2. Connect the reader
3. Unplug the terminal from the dock 
4. Try create to a payment 

**Observed behavior**

The reader never replies the payment request.
The plugin never replies and  few minutes after I receive error in the logs and the reader is disconnected.
As I see, the plugin tries to ping the ethernet address which is not available anymore.

Few minutes after the reader is unexpectedly disconnected.

If I try to reconnect the reader while not being on the dock, then the initial IP linked will be the Wifi's one so I can safely plug/unplug my reader without having any connection issue.

**Expected behavior**

Be able the switch with ou without ethernet dock without connection issue

This behavior should be working as stipulated in the [docs](https://stripe.com/docs/terminal/payments/setup-reader/bbpos-wisepos-e#network-priority)

**Screenshots**

![IMG_2652](https://user-images.githubusercontent.com/16417139/204034569-949e7f18-152b-4cba-893f-356af9f07f19.jpeg)

Discovery with the Dock

<img width="416" alt="image" src="https://user-images.githubusercontent.com/16417139/204034631-ec4d7f77-6b96-499d-bdd0-5b1acf7fb380.png">

Discovery without the Dock

<img width="422" alt="image" src="https://user-images.githubusercontent.com/16417139/204034995-9ceec2d9-cf5c-4b3a-b408-c186938c8a95.png">

Some hints /helps is more than welcome 🙏 

I have the same issue for [@stripe/terminal-js](https://www.npmjs.com/package/@stripe/terminal-js)

**Comment by nazli-stripe** [comment]
Unfortunately this is the expected behavior. The SDK uses the IP address of the reader to send commands and this changes when you switch from ethernet to IP or vice versa. Internally we are looking into making this experience better but don't have any concrete plans or timeline for a fix. All SDKs will run into this issue with internet readers, but you can use the server-driven integration to circumvent it instead: https://support.stripe.com/questions/terminal-server-driven-integration
