### ISSUE TITLE
Connected Reader Information Realtime Update

### ISSUE THREAD

**Issue by trungh97** [stripe/stripe-terminal-react-native#459]
Hello!

I saw that after connecting to a reader successful:

- The battery does not seem to be updated real-time. I have to disconnect and connect again to see the latest battery number.
- The same for Available Update version, I chose **optional update** to test the firmware update. When I updated successfully, the **connectedReader** object still contains the `avaiableUpdate `object.

Please help me to confirm if I did something wrong. Thanks!

**Comment by bric-stripe** [comment]
👋 Hi, the battery status is only polled once every 10 minutes while connected. This is to conserve battery itself since the reader will go in to a lower power idle state while connected but when not receiving any requests. Note that within 10 minutes the battery % may of course not change and no update will be announced. The recommendation for testing this is to connect with the reader plugged in, let it succeed connecting, unplug the reader and then wait 10m. Since you explicitly changed it from the charging to not charging state that update should be announced on the next polling of the battery status.

The `availableUpdate` still being present after installing the update sounds like a bug in the SDK and we'll investigate that.

**Comment by trungh97** [comment]
Thanks @bric-stripe, I'll give it a try!

**Comment by trungh97** [comment]
@bric-stripe Hi! Looks like your testing recommendation above is not working, I have connected to a reader plugged in, then unplugged it after connecting successfully, but nothing changes after 1 hour.

**Comment by bric-stripe** [comment]
@trungh97 I'll to reproduce. Are you seeing that with both iOS and Android or what platform were you testing on?

**Comment by trungh97** [comment]
@bric-stripe I'm working on iOS, and I use React Native.

**Comment by bric-stripe** [comment]
@trungh97 thanks. Sorry about the bad info here. I was mistaken, the `didReportBatteryLevel` callback from the native SDKs is not wired up in the RN SDK yet. Tagging this as a feature to get added but I don't have an ETA on when this will be available.

**Comment by trungh97** [comment]
thanks for your information, so I'll assume that the battery realtime update has not supported RN yet, and I'll go with the current approach until we get the update in the next versions.

**Comment by Dhaval1905** [comment]
@trungh97  would you please share your code here how you have achieve the connect reader functionality. I am facing lots of issue to read my card data and redaer information.

**Comment by nazli-stripe** [comment]
@trungh97 we just released `beta.19` with support for real time connected reader updates when retrieving the reader with `getConnectedReader`. We also added a callback for `onUpdateReaderBatteryLevel`! 

Changelog: https://github.com/stripe/stripe-terminal-react-native/releases/tag/v0.0.1-beta.19
