### ISSUE TITLE
Android build failure with 0.0.1-beta.12, Expo

### ISSUE THREAD

**Issue by nprail** [stripe/stripe-terminal-react-native#477]
**Describe the bug**
When attempting to build in an Expo app on Android, the following error occurs:

```
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties' from inputs:
      - /Users/nprail/.gradle/caches/transforms-3/9314ebc5fafe4a65de1c36cd8bab2f4d/transformed/jetified-stripeterminal-localmobile-2.20.1/jars/classes.jar
      - /Users/nprail/.gradle/caches/transforms-3/d67656dc5217008b8b17f4eb57d4d252/transformed/jetified-bcprov-jdk15to18-1.69.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.4/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
```

**To Reproduce**

1. Create an Expo project (specifically `expo@48.0.18`)
2. Install `@stripe/stripe-terminal-react-native@0.0.1-beta.12`
3. Run `npx expo prebuild -p android`
4. Run Android with `npx expo run:android`
5. Build fails with the above error

**Expected behavior**

The build should succeed :)

**Stripe Terminal React Native SDK version**

- 0.0.1-beta.12

**Smartphone (please complete the following information):**

N/A, build failure

**Additional context**
Other dependencies in the project:

```
├── @expo/react-native-action-sheet@4.0.1
├── @expo/vector-icons@13.0.0
├── @react-native-async-storage/async-storage@1.17.11
├── @react-navigation/bottom-tabs@6.5.7
├── @react-navigation/native-stack@6.9.12
├── @react-navigation/native@6.1.6
├── @rneui/base@4.0.0-rc.7
├── @rneui/themed@4.0.0-rc.7
├── @stripe/stripe-react-native@0.27.1
├── @stripe/stripe-terminal-react-native@0.0.1-beta.12
├── expo-barcode-scanner@12.3.2
├── expo-blur@12.2.2
├── expo-build-properties@0.6.0
├── expo-camera@13.2.1
├── expo-splash-screen@0.18.2
├── expo-status-bar@1.4.4
├── expo@48.0.18
├── react-native-keyboard-aware-scroll-view@0.9.5
├── react-native-safe-area-context@4.5.0
├── react-native-screens@3.20.0
├── react-native-signature-capture@0.4.12
├── react-native-sound@0.11.2
├── react-native-url-polyfill@1.3.0
├── react-native@0.71.8
├── react@18.2.0
```

**Comment by andrewchester1** [comment]
Hi @nprail,
I ran into the same issue with expo, and have found a solution. This issue will cause all builds(local and eas) to fail, and can not be easily fixed for expo managed mobile apps. This is a big issue for Production apps, and is disappointing that a fix has not been added to the library, or given actual direction for the specific framework. This issue and solution should be added to the readme since eas builds do not work, and makes this library not usable for expo applications without ejecting.

Solution: 
1. Add expo-build-properties library to project.
2. Add the code below to your app.json inside the "expo" object.
```
"plugins": [
  [
     "expo-build-properties",
     {
	  "android": {
		  "packagingOptions": {
			  "exclude": ["org/bouncycastle/x509/CertPathReviewerMessages*"]
		  }
	  }
     }
  ]
]
```
3. delete android folder and rebuild.

Note: I have had many issues along these lines with this library. I understand that this is a beta library and have worked with many beta libraries in the past. I do not expect this library to be perfect, but the documentation and communication from the developers has been frustrating and not very helpful. If you are looking into using terminals with an expo application, I would recommend looking into different solutions. I hope solution helps other developers

**Comment by ts-candide** [comment]
Another option is to use the `pickFirst` strategy for the packagingOptions, which ensures that the first matching result is included in the resulting apk:

```js
"plugins": [
  [
     "expo-build-properties",
     {
	  "android": {
		  "packagingOptions": {
			  "pickFirst": ["org/bouncycastle/x509/CertPathReviewerMessages*"]
		  }
	  }
     }
  ]
]
```
