### ISSUE TITLE
An unexpected SDK error occured when use method connectBluetoothReader in ios

### ISSUE THREAD

**Issue by tmbax0098** [stripe/stripe-terminal-react-native#489]
**Describe the bug**

React native **0.71.10**
stripe library version :  **^0.0.1-beta.12**
Stripe Reader **Wise pad 3**
**Ios part**

we create an application to pay orders.
we use bluetooth to connect with reader
in android platform every thing is ok.

**in ios platform error occured while connect to reader**

This error occured after this method  : 

**const { reader, error } = await connectBluetoothReader({
      reader: selectedReader,
      locationId: locationReference
    });**

Erorr message is : **An unexpected SDK error occured**

**To Reproduce**

1. initial react native app
2. install stripe lib
3. create a page and discover readers
4. try connect to a reader ( try on ios )

**Expected behavior**
we expected that devices connect successfully.

**Screenshots**
[https://ibb.co/DwtqSQG](https://ibb.co/DwtqSQG)

**Stripe Terminal React Native SDK version**

- (e.g., `^0.0.1-beta.12`)

**Smartphone:**

- Device: [e.g. iPhone14]
- OS: [e.g. iOS16.5.1]

**Comment by bric-stripe** [comment]
👋 are you able to reproduce this with the example app? Regardless, could you share the WisePad 3 serial number you're hitting this with? With that we can look up some logs to try to debug.

**Comment by bric-stripe** [comment]
realized a bug in the native iOS SDK that returns this unexpected SDK error instead of the expected [`SCPErrorMustBeDiscoveringToConnect`](https://stripe.dev/stripe-terminal-ios/1.4.0/Enums/SCPError.html#/c:@E@SCPError@SCPErrorMustBeDiscoveringToConnect). If you're canceling the discoverReaders command before calling connect that would explain things. For the underlying native iOS SDK the discoverReaders call must continue running when you call connect. This will work on Android as well, but Android also supports connecting after canceling discover which would explain why this is working OK on Android.

We'll be syncing up the native platforms in a future release. For now, to work around that iOS/Android inconsistency, you'll need to stop canceling discoverReaders before calling connectBluetoothReader. Instead let the discoverReaders keep running when calling connectBluetoothReader.

We'll also get the unexpected SDK error reporting the expected error correctly in an update.

**Comment by tmbax0098** [comment]
Hello
Thank you for your help
**I will modify and test the program codes in the manner you explained and report the results here.**

**Comment by Dhaval1905** [comment]
@tmbax0098  Which reader are you use to connect reader? Also would you please share your code so I can help you for stripe terminal regarding things

**Comment by tmbax0098** [comment]
> realized a bug in the native iOS SDK that returns this unexpected SDK error instead of the expected [`SCPErrorMustBeDiscoveringToConnect`](https://stripe.dev/stripe-terminal-ios/1.4.0/Enums/SCPError.html#/c:@E@SCPError@SCPErrorMustBeDiscoveringToConnect). If you're canceling the discoverReaders command before calling connect that would explain things. For the underlying native iOS SDK the discoverReaders call must continue running when you call connect. This will work on Android as well, but Android also supports connecting after canceling discover which would explain why this is working OK on Android.
> 
> We'll be syncing up the native platforms in a future release. For now, to work around that iOS/Android inconsistency, you'll need to stop canceling discoverReaders before calling connectBluetoothReader. Instead let the discoverReaders keep running when calling connectBluetoothReader.
> 
> We'll also get the unexpected SDK error reporting the expected error correctly in an update.

I changed my program.
**I ran discover method and readers were found, (whitout calling cancel discover method) I called connectBluetoothReader and connected successfully**

Thank you  Brain Cook and Stripe team for your support.
