### ISSUE TITLE
Issue with Implementing "Tap to Pay" using Stripe Terminal in React Native App

### ISSUE THREAD

**Issue by Brunowilliang** [stripe/stripe-terminal-react-native#589]
Environment:

Expo with Dev Client
Physical iOS Device - iPhone 12
@stripe/stripe-terminal-react-native version 0.0.1-beta.14
Issue Description:

I am working on a React Native project where I'm implementing the "Tap to Pay" feature using the @stripe/stripe-terminal-react-native library (version 0.0.1-beta.14). The app is being developed with Expo and tested on a physical iOS device. I am encountering a problem with the discoverReaders method while trying to implement this functionality.

```tsx
  const { discoverReaders, cancelDiscovering } = useStripeTerminal({
    onUpdateDiscoveredReaders: (readers) => {
      console.log('onUpdateDiscoveredReaders', readers)
    },
  })

  useEffect(() => {
    console.log('Starting reader discovery...')

    const discover = async () => {
      console.log('Calling discoverReaders...')
      let isTimeout = false

      const timeout = setTimeout(() => {
        isTimeout = true
        console.log('Reader discovery timeout.')
      }, 5000)

      const { error } = await discoverReaders({
        discoveryMethod: 'localMobile',
        simulated: false,
      })

      clearTimeout(timeout)

      if (isTimeout) {
        console.log('Reader discovery was interrupted due to timeout.')
        return
      }

      if (error) {
        console.log('Error discovering readers:', error)
      } else {
        console.log('discoverReaders called successfully.')
      }
    }

    discover()

    return () => {
      console.log('Cancelling reader discovery...')
      cancelDiscovering()
    }
  }, [discoverReaders, cancelDiscovering])
```

my logs:
```shell
 LOG  Starting reader discovery...
 LOG  Calling discoverReaders...
 LOG  Reader discovery timeout.
 ```

Behavior Observed:
When attempting to discover readers for "Tap to Pay", the discoverReaders function is called, but it does not complete its operation. Instead, it times out after 5 seconds without discovering any readers or returning any relevant errors, except for the timeout notification. This issue persists despite the presence of Stripe readers in proximity and operational.

Steps to Reproduce:
Launch the app on a physical iOS device.
Initiate the "Tap to Pay" process.
Trigger the discoverReaders function.
Observe the process timing out without discovering any Stripe readers.
Expected Behavior:
The expectation is for the discoverReaders function to successfully detect available Stripe readers for "Tap to Pay" without prematurely timing out, considering that the readers are within range and fully functional.

Any advice or suggestions on how to troubleshoot and resolve this issue would be greatly appreciated. If further details or logs are required, I am ready to provide them.

**Comment by itbeginswithi** [comment]
Hi @Brunowilliang,
The reason you don't see error logs is due to the return; statement inside the if (isTimeout) condition, this terminates the function prematurely, and prevents further execution of the function logic, including handling the case where the discoverReaders operation is successful.

**Comment by itbeginswithi** [comment]
Hi @Brunowilliang,
The reason you don't see error logs is due to the return; statement inside the if (isTimeout) condition, this terminates the function prematurely, and prevents further execution of the function logic, including handling the case where the discoverReaders operation is successful.

 Instead of immediately returning from the function, you could log the timeout message and continue with any necessary cleanup or error handling.
 
 Example:
 `
   if (isTimeout) {
     console.log('Reader discovery was interrupted due to timeout.')
  }
  // Continue with the rest of the function logic, even if a timeout occurred
 `

**Comment by itbeginswithi** [comment]
Hi @Brunowilliang,
The reason you don't see error logs is due to the return; statement inside the if (isTimeout) condition, this terminates the function prematurely, and prevents further execution of the function logic, including handling the case where the discoverReaders operation is successful.

Instead of immediately returning from the function, you could log the timeout message and continue with any necessary cleanup or error handling.

Example:
```
  if (isTimeout) {
    console.log('Reader discovery was interrupted due to timeout.')
 }
 // Continue with the rest of the function logic, even if a timeout occurred
```

**Comment by Brunowilliang** [comment]
@itbeginswithi This error is occurring after some time with the app open, so I have to restart it to resolve it.

When restarting it gives this error:
```shel
 LOG  Starting reader discovery...
 LOG  Calling discoverReaders...
 LOG  secret pst_test_YWNjdF8xTU1xekJKYldlTmpUY1JMLDl3eW1BeXpXQ2ZaMks0OThCVEN2ZVhJZHQxeEt5bm8_00iBU59Qlf
 LOG  Error discovering readers: {"code": "CommandNotAllowed", "message": "Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid."}
 LOG  [Stripe terminal]: didFinishDiscoveringReaders {"error": {"code": "CommandNotAllowed", "message": "Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid."}}
```

Do you know how I can resolve this error?

**Comment by itbeginswithi** [comment]
It appears that reader discovery is not permitted, possibly due to a configuration oversight. 
Here are two steps to address this:

1. Confirm that the Stripe Terminal has been initialized.
2. Verify that you have included the configuration plugin in the array of your app.json.
Refer to the documentation for more details: [Stripe Terminal Integration Setup](https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=react-native#configure) (Select the Expo tab).

**Comment by Brunowilliang** [comment]
@itbeginswithi  I checked all this, the terminal starts, I get the token but it doesn't work, I added updated logs for you to see:

```shell
iOS Bundling complete 13387ms
 LOG  secret pst_test_YWNjdF8xTU1xekJKYldlTmpUY1JMLDRKZXZsN0Z3UEp1OFRzNXNpZmlndlRtN09BMDdLTzI_00LDdXPKCZ
 LOG  [Stripe terminal]: didChangeOfflineStatus {"reader": undefined, "sdk": {"networkStatus": "unknown", "offlinePaymentAmountsByCurrency": {}, "offlinePaymentsCount": 0}}
 LOG  [Stripe terminal]: didChangeOfflineStatus {"reader": undefined, "sdk": {"networkStatus": "online", "offlinePaymentAmountsByCurrency": {}, "offlinePaymentsCount": 0}}
 LOG  secret pst_test_YWNjdF8xTU1xekJKYldlTmpUY1JMLHRFTWhQU2dneVJ6cjd5dVVsc1E1VHNYVWJZbUFqa20_00P0CufCIe
 LOG  Starting reader discovery...
 LOG  Calling discoverReaders...
 LOG  Error discovering readers: {"code": "CommandNotAllowed", "message": "Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid."}
 LOG  [Stripe terminal]: didFinishDiscoveringReaders {"error": {"code": "CommandNotAllowed", "message": "Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid."}}
```

I'm testing on my physical device with expo --dev-client

**Comment by itbeginswithi** [comment]
It appears that you're currently testing your application on the Expo Go app. To be able to use the Stripe Terminal, you'll need to build your app because the SDK interacts with native code. 
For additional information, refer to the [Stripe documentation](https://stripe.com/docs/terminal/payments/setup-integration?terminal-sdk-platform=react-native#build).

**Comment by Brunowilliang** [comment]
@itbeginswithi  I'm not using expo go, I generated a build and I'm testing it with the physical device

**Comment by albertpco** [comment]
@Brunowilliang I had this issue, did you check that you have the entitlement for dev environment from Apple?

**Comment by nazli-stripe** [comment]
hey @Brunowilliang are you still running into this issue? Checking the entitlements is a good starting point, [here](https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=ios#entitlements-build-file) is what you need for Tap to Pay on iOS. For issues like this we recommend first reaching out to [support@stripe.com](mailto:support@stripe.com) as the fastest way of getting help.

**Comment by albertpco** [comment]
@nazli-stripe integrating tap to pay has been a huge blocker for my application and I've reached out multiple times to the support team. Can you or the team please provide an example of just getting Tap to Pay to work in a screen in react native? Docs are quite unclear

**Comment by nazli-stripe** [comment]
@albertpco we have Tap to Pay working on our example-app and dev-app examples. Have those examples been helpful to give an idea? What exactly are you running into issues?
