### ISSUE TITLE
MEtadata not being sent to payment intent

### ISSUE THREAD

**Issue by kitzj** [stripe/stripe-terminal-react-native#607]
**Describe the bug**
I can assign the metadata to a (client side) payment intent, but when I check the logs in the Stripe dashboard, it's always blank.

**To Reproduce**

Create a client-side payment intent, assign metadata, and check the stripe dashboard logs to see if it's there.

**Expected behavior**
Metadata should be there.

**Stripe Terminal React Native SDK version**

`^0.0.1-beta.14`

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: 17.2.1

**Comment by nazli-stripe** [comment]
@kitzj are you still running into this issue? We are not able to reproduce it locally, and can create client-side PaymentIntents with metadata. For potential integration issues we recommend reaching out to support@stripe.com first. If the issue is not resolved after that, feel free to open another ticket.
