### ISSUE TITLE
Endless NETWORK_ERROR.CONNECTION_TOKEN_PROVIDER_ERROR on connectBluetoothReader after bundle reload in Expo 

### ISSUE THREAD

**Issue by Noitidart** [stripe/stripe-terminal-react-native#644]
**Describe the bug**
When I push a remote update via EAS (Expo), beofore calling Expo's `Updates.reloadAsnc` which reloads the app bundle, I call `disconnectReader`. Then on startup of, I call `initialize`, `discoverReaders`, and then `connectBluetoothReader`. The `connectBluetoothReader` endlessly resolves with this error response:

```
{
  error: {
    code: NETWORK_ERROR.CONNECTION_TOKEN_PROVIDER_ERROR,
    message: Timed out waiting for connection token
  }
}
```

If I hard close the app, and re-launch it, it does the same three calls and succeeds very fast. So internet connectivity is not a problem. This happens on two my touchscreens. One is hard wired ethernet, the other is wifi.

**To Reproduce**
Steps to reproduce the behavior: It doesn't happen all the time, but eventually an app bundle reload as I described above does this.

1. Please see the above description.

**Expected behavior**
When interent is good, it should not resolve with error of `NETWORK_ERROR.CONNECTION_TOKEN_PROVIDER_ERROR`. 

**Screenshots**

**Stripe Terminal React Native SDK version**

- "@stripe/stripe-terminal-react-native": "^0.0.1-beta.14",
- "react-native": "0.72.4",
- "expo": "~49.0.11",

**Smartphone (please complete the following information):**

- Device: Android Touchscreen
- OS: Android 12

**Additional context**

Is there maybe other steps other than `disconnectReader` I should call before reloading the app bundle?

**Comment by Noitidart** [comment]
I think I solved this, I think it was my retry strategy over retrying.

**Comment by sammy-black** [comment]
> I think I solved this, I think it was my retry strategy over retrying.

I am experiencing similar issue now but i am unable to fix it. what do you mean by  "retry strategy over retrying"
![WhatsApp Image 2024-08-21 at 16 05 33_ac0409d7](https://github.com/user-attachments/assets/fcb1c61b-acfd-4c98-9e77-29f29c4adf3e)

**Comment by sammy-black** [comment]
> I think I solved this, I think it was my retry strategy over retrying.

I am experiencing similar issue now but i am unable to fix it. what do you mean by "retry strategy over retrying"
![WhatsApp Image 2024-08-21 at 16 05 33_ac0409d7](https://github.com/user-attachments/assets/f3935cfc-6b06-4ac1-ae40-6fd409eeab42)

**Comment by ashwinramdas12** [comment]
> > I think I solved this, I think it was my retry strategy over retrying.
> 
> I am experiencing similar issue now but i am unable to fix it. what do you mean by "retry strategy over retrying" ![WhatsApp Image 2024-08-21 at 16 05 33_ac0409d7](https://github.com/user-attachments/assets/f3935cfc-6b06-4ac1-ae40-6fd409eeab42)

Hi @sammy-black did you ever fix this issue?

**Comment by sammy-black** [comment]
I am not sure why I was getting the error at that time because the token was being sent from the backend, and it wasn't connecting. I later used the example app provided by Stripe as the boilerplate for my project. I customized it to fit the UI I wanted, and it has been working fine ever since
Here is the link to the example app: https://github.com/stripe/stripe-terminal-react-native/tree/main/example-app
[https://opengraph.githubassets.com/28cd87567a09e37e99907dadffca5f971756de7dd0e19d25b2204819cdb0f224/stripe/stripe-terminal-react-native]<https://github.com/stripe/stripe-terminal-react-native/tree/main/example-app>
stripe-terminal-react-native/example-app at main · stripe/stripe-terminal-react-native<https://github.com/stripe/stripe-terminal-react-native/tree/main/example-app>
React Native SDK for Stripe Terminal. Contribute to stripe/stripe-terminal-react-native development by creating an account on GitHub.
github.com

________________________________
